# Generated by Django 5.1.3 on 2025-01-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_images/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="label",
            field=models.ManyToManyField(blank=True, null=True, to="main.label"),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variation",
            name="stock",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
