# Generated by Django 5.1.3 on 2025-01-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name="Variation",
        ),
    ]
