# Generated by Django 5.1.3 on 2025-01-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_product_slug_delete_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deneme",
            field=models.TextField(null=True),
        ),
    ]
