# Generated by Django 5.1.3 on 2025-01-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_user_alter_product_deneme"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
