# Generated by Django 5.1.3 on 2025-01-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="label",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Label",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
